### ISSUE TITLE
Add comments to posts (server)

### ISSUE THREAD

**Issue by d-username** [boolean-uk/team-dev-server#115]
## User Story
-->  As a user, so I can interact with others, I want to be able to comment on posts.

## Requirements
--> Can add comments on posts up to 150 characters  
--> Cannot reply to other comments for now - comments are single-threaded  
--> Comments should be displayed most recent first
--> Comments should show the users name and the time the comment was made.
--> Only the first comment is shown by default, along with the number of comments

**Comment by Hoolio333** [comment]
PLAN:

1. team-dev-server/prisma/schema.prisma - we create a model for PostComment - this will follow the format of the ERD from assets/ERD.png
2. PostComment will have columns: id, content, postId, userId, updatedAt, createdAt, profileId.
3. PostComments will be relating to User (userId) and Post (postId) and Profile (profileId) via foreign keys
4. The “content” in PostComment will be a string and have a maximum length of 150 attribute
5. npx prisma migrate
6. npx prisma migrate dev --name add_post_comment_to_schema 
7. team-dev-server/src/index.js - express set up is already implemented
8. team-dev-server/src/routes/post.js - here are the routers leading to the next step
9. team-dev-server/src/constollers/post/comment.js - we will write the code in the file
10. Create class Comment in Comment.js (to keep the same theme as Post.js with its own class)
11. Create async function within the Comment class, which will return the comment object (including Comment ID, profile ID, updatedAt, createdAt, userID)
12. Include error handling within the function.

**Comment by Auenc** [comment]
> PostComments will be relating to User (userId) and Post (postId) and Profile (profileId) via foreign keys

You won't need to associate the Comment with a Profile because a User is associated with a Profile. Therefore, you'll be able to include the profile via the user.

**Comment by d-username** [comment]
We linked the Comment to Profile because in the Comments we would need access to the Profile and this way it is more direct than going through Comment --> User --> Profile.

Is this implementation OK? Or do you suggest leaving the User out?

**Comment by Auenc** [comment]
I would say that you need to keep the connection between Comment and User (because fundamentally a User is who is posting a comment). That being said, there is an argument to be had here that, by storing both the Use and Profile IDs, we're using more storage in our database than needed per comment created in the system. The difference between the two options would be as follows:

Having both the User and Profile IDs on the comment
```js
prisma.comments.findMany({
include: {
   user: true,
   profile: true
}
})
```

Versus just having the User id associated to a comment:
```js
prisma.comments.findMany({
include: {
   user: {
       include: {
          profile: true
       }
   },
}
})
```

So you would be saving a few characters in code, at the expense of ~4bytes per comment. Which is very little, but when you have millions of comments, that size will start to increase significantly. Obviously, for project, we're _very_ unlikely to get anywhere near that many comments, but just to illustrate why it would be better to keep the number of columns on a table to only the ones required.
